### GET request to example server
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "email": "furiosa5@gmail.com",
  "password": "mommy magnificant",
  "firstName": "Furi",
  "lastName": "OSA"
}
###